pull_request_rules:
  - name: merge [bot] PRs when CI pass
    conditions:
      - check-success = "Check helpers"
      - check-success = "check-macos-linux-build"
      - check-success = "check-macos-linux-docker"
      - check-success = "check-macos-linux-editable"
      - check-success = "check-macos-linux-nix"
      - check-success = "check-macos-linux-sdist"
      - check-success = "lint"
      - check-success = "pre-commit.ci - pr"
      - or:
          - approved-reviews-by = nim65s
          - author = nim65s
          - author = dependabot[bot]
          - author = github-actions[bot]
          - author = hrp2-14
          - author = pre-commit-ci[bot]
    actions:
      merge:
