name: Test editable with example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  editable:
    name: Editable ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8","3.9","3.10", "3.11", "3.12", "3.13"]
    env:
      SYSTEM_VERSION_COMPAT: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup
        run: |
          python -m pip install -U pip
          python -m pip install -U wheel
      - name: build cmeel wheel
        run: python -m pip wheel -w $HOME/wh .
      - name: install cmeel
        run: python -m pip install $HOME/wh/cmeel*.whl
      - name: clone cmeel-example
        run: git clone --recursive -j2 https://github.com/cmake-wheel/cmeel-example
      - name: install cmeel-example in editable mode
        run: cd cmeel-example && python -m pip install --editable .
      - name: test module
        run: python -c "import cmeel_example; assert cmeel_example.cmeel_add(3, 4) == 7"
      - name: update source
        run: echo "def incr_add(a, b):return cmeel_add(a, b) + 1" >> cmeel-example/python/cmeel_example/__init__.py
      - name: test updated module
        run: python -c "import cmeel_example; assert cmeel_example.incr_add(3, 4) == 8"
