name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        #python-version: ["3.8","3.9","3.10"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup
        run: |
          python -m pip install -U pip
          python -m pip install -U ninja packaging tomli cmake wheel
      - run: python -m pip install .
      - run: python -m pip install --no-build-isolation git+https://github.com/cmake-wheel/cmeel-example@topic/win2
        env:
          CMAKE_GENERATOR: Ninja
      #- run: cmeel-add 3 4
      - run: python -c "import cmeel_example; assert cmeel_example.cmeel_add(3, 4) == 7"
