name: Test with example

on: ["push", "pull_request"]

jobs:
  test:
    name: Test ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        #python-version: ["3.8","3.9","3.10"]
        #os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10"]
        os: ["windows-latest"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup
        run: |
          python -m pip install -U pip
          python -m pip install -U ninja packaging tomli cmake wheel
      - run: python -m pip install .
      - run: python -m pip install --no-build-isolation git+https://github.com/cmake-wheel/cmeel-example@topic/win2
        env:
          CMAKE_GENERATOR: Ninja
          CXXFLAGS: "/d2FH4-"
      - name: test module
        run: python -c "import cmeel_example; assert cmeel_example.cmeel_add(3, 4) == 7"
      - name: test executable
        run: cmeel-add 3 4
